"""Configurable header banner for generated files."""

from __future__ import annotations

from dataclasses import dataclass

DEFAULT_HEADER_TEMPLATE = """\
# Auto-generated by pycodelift from {relative_path}.
# Do NOT edit; changes will be overwritten on regeneration.
"""


@dataclass
class HeaderTemplate:
    """Banner with ``{relative_path}`` and ``{short_name}`` slots."""

    template: str = DEFAULT_HEADER_TEMPLATE

    def render(self, *, relative_path: str, short_name: str) -> str:
        return self.template.format(relative_path=relative_path, short_name=short_name)


__all__ = ["DEFAULT_HEADER_TEMPLATE", "HeaderTemplate"]
